// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAea9yMRo4rEWH6lzy97VW-KKD--1EdB-g',
    appId: '1:341312793830:web:695e1e76993f4a44af5f27',
    messagingSenderId: '341312793830',
    projectId: 'fitcalc-project-468408',
    authDomain: 'fitcalc-project-468408.firebaseapp.com',
    storageBucket: 'fitcalc-project-468408.firebasestorage.app',
    measurementId: 'G-WBP30920CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYIB3NeelGTJsYL9GxODpjnLEudFpz_8',
    appId: '1:341312793830:android:4c0b9ab85b0c9d02af5f27',
    messagingSenderId: '341312793830',
    projectId: 'fitcalc-project-468408',
    storageBucket: 'fitcalc-project-468408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Q3MH-yujxHL--GSsNJWKZxRZtpkS8HE',
    appId: '1:341312793830:ios:3498cdea8e55fda7af5f27',
    messagingSenderId: '341312793830',
    projectId: 'fitcalc-project-468408',
    storageBucket: 'fitcalc-project-468408.firebasestorage.app',
    iosBundleId: 'com.example.fitcalc',
  );
}
