name: Build and Test FitCalc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          cache: true

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - name: Build Android App Bundle
        if: matrix.os == 'ubuntu-latest'
        run: flutter build appbundle --obfuscate --split-debug-info=build/symbols --no-codesign # Questo permetterà alla build di completarsi producendo un AAB non firmato

      - name: Upload symbol map
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: fitcalc-symbol-map
          path: build/symbols
