name: Build and Test FitCalc

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    name: Build on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: "stable"
          version: "3.x"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android App Bundle
        if: matrix.os == 'ubuntu-latest'
        run: flutter build appbundle --obfuscate --split-debug-info=build/symbols

      - name: Upload symbol map
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: fitcalc-symbol-map
          path: build/symbols
